
import { getPrograms, getProgramById, getAllSessionsForProgram, getSessionById } from './api/programs';
import { getLessonCategoriesWithLessons } from './api/library';
import { enrollInProgram, unenrollFromProgram } from './api/auth';
import {
  getActiveEnrollment,
  getTodaySession,
  completeSession,
  getUserProfile,
  updateUserProfile,
  uploadAvatar,
  getUserBadges,
  getUserPRs,
  createPR,
  updatePR,
  deletePR,
  getUserObjectives,
  createObjective,
  updateObjective,
  deleteObjective,
  getPublicUserProfile,
  searchUsers,
  getFriends,
  addFriend,
  removeFriend,
  respondToFriendRequest,
  getUserAchievements,
  getUserAchievementStats,
  getProgramEnrolledStudents
} from './api/user';
import { 
  getEnrolledStudents,
  adminGetAllPrograms,
  adminCreateProgram,
  adminUpdateProgram,
  adminDeleteProgram,
  adminGetProgramWithWeeksAndSessions,
  adminUpdateSession,
  adminGetAllLessonCategories,
  adminCreateLessonCategory,
  adminUpdateLessonCategory,
  adminDeleteLessonCategory,
  adminCreateLesson,
  adminUpdateLesson,
  adminDeleteLesson,
  getProgramEnrollments,
  getSessionProgress
} from './api/admin';

export {
  getPrograms,
  getProgramById,
  getAllSessionsForProgram,
  getSessionById,
  getLessonCategoriesWithLessons,
  enrollInProgram,
  unenrollFromProgram,
  getActiveEnrollment,
  getTodaySession,
  completeSession,
  getUserProfile,
  updateUserProfile,
  uploadAvatar,
  getUserBadges,
  getUserPRs,
  createPR,
  updatePR,
  deletePR,
  getUserObjectives,
  createObjective,
  updateObjective,
  deleteObjective,
  getPublicUserProfile,
  searchUsers,
  getFriends,
  addFriend,
  removeFriend,
  respondToFriendRequest,
  getEnrolledStudents,
  getUserAchievements,
  getUserAchievementStats,
  getProgramEnrolledStudents,
  adminGetAllPrograms,
  adminCreateProgram,
  adminUpdateProgram,
  adminDeleteProgram,
  adminGetProgramWithWeeksAndSessions,
  adminUpdateSession,
  adminGetAllLessonCategories,
  adminCreateLessonCategory,
  adminUpdateLessonCategory,
  adminDeleteLessonCategory,
  adminCreateLesson,
  adminUpdateLesson,
  adminDeleteLesson,
  getProgramEnrollments,
  getSessionProgress
};
